export const DEMO_WORKSPACE = {
  "version": 12,
  "id": "patchbay_demo_ai_tests_rfc",
  "name": "Demo \u00b7 Should AI agents write our test suites?",
  "nodes": [],
  "connections": [
    {
      "id": "conn_src_to_ai1",
      "sourceId": "cell_src_rfc",
      "targetId": "cell_ai_1",
      "label": "source",
      "createdAt": 1778710000000,
      "gate": "open"
    },
    {
      "id": "conn_src_to_ai2",
      "sourceId": "cell_src_rfc",
      "targetId": "cell_ai_2",
      "label": "source",
      "createdAt": 1778710000000,
      "gate": "open"
    },
    {
      "id": "conn_src_to_ai3",
      "sourceId": "cell_src_rfc",
      "targetId": "cell_ai_3",
      "label": "source",
      "createdAt": 1778710000000,
      "gate": "open"
    },
    {
      "id": "conn_src_to_ai4",
      "sourceId": "cell_src_rfc",
      "targetId": "cell_ai_4",
      "label": "source",
      "createdAt": 1778710000000,
      "gate": "open"
    }
  ],
  "viewport": {
    "x": -20,
    "y": 0,
    "zoom": 0.62
  },
  "cells": [
    {
      "id": "cell_src_rfc",
      "type": "source",
      "title": "RFC: AI-written test suites",
      "content": "## RFC: Let Claude write the test suite for new endpoints\n\n**Author:** platform-eng@  \u00b7  **Status:** Draft  \u00b7  **Decide by:** end of sprint\n\n### Current state\n\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\n- Engineers spend ~25% of feature time writing tests\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\n- Senior devs complain about \"happy path bias\" in junior-written tests\n\n### Proposal\n\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\n\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\n- **Owner:** developer-experience team\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\n\n### Decision needed\n\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\nlibrary + Copilot rules instead?\n",
      "position": {
        "x": 560,
        "y": 60
      },
      "createdAt": 1778710000000,
      "updatedAt": 1778710000000,
      "output": {
        "status": "success",
        "text": "## RFC: Let Claude write the test suite for new endpoints\n\n**Author:** platform-eng@  \u00b7  **Status:** Draft  \u00b7  **Decide by:** end of sprint\n\n### Current state\n\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\n- Engineers spend ~25% of feature time writing tests\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\n- Senior devs complain about \"happy path bias\" in junior-written tests\n\n### Proposal\n\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\n\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\n- **Owner:** developer-experience team\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\n\n### Decision needed\n\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\nlibrary + Copilot rules instead?\n",
        "durationMs": 0
      },
      "dimensions": {
        "width": 420,
        "height": 360
      }
    },
    {
      "id": "cell_ai_1",
      "type": "ai",
      "title": "Steelman: pilot it",
      "instruction": "Steelman the case FOR letting AI write our test suites.",
      "provider": "anthropic",
      "model": "claude-sonnet-4-20250514",
      "outputMode": "text",
      "position": {
        "x": 100,
        "y": 520
      },
      "createdAt": 1778710000000,
      "updatedAt": 1778710000000,
      "output": {
        "status": "success",
        "text": "**The strongest case for shipping this isn't that AI writes better tests \u2014 it's that it changes which tests get written.**\n\nHand-written tests are biased toward the cases the author *thought of*. AI-generated tests are biased toward the cases the *handler's surface area implies*. Different bias, broader coverage.\n\nThree load-bearing arguments:\n\n1. **It moves the bottleneck.** Right now the slow step is *writing*, not *reviewing*. Inverting that lets a senior reviewer go through 4\u00d7 the routes per hour. Your senior bench becomes more leveraged, not more loaded.\n\n2. **Error-path coverage will jump.** Engineers under deadline pressure skip the 401/403/422 branches. A Sonnet given the OpenAPI schema *always* writes them. The 71% coverage problem is concentrated exactly where AI is consistent and humans are inconsistent.\n\n3. **The kill-switch makes it cheap to try.** Env flag, 5-minute revert. The downside of being wrong about this for one sprint is 3 weeks of work; the downside of being right and not trying is 18 months of slower delivery.",
        "durationMs": 4550
      },
      "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
      "dimensions": {
        "width": 360,
        "height": 480
      }
    },
    {
      "id": "cell_ai_2",
      "type": "ai",
      "title": "Steelman: don't",
      "instruction": "Steelman the case AGAINST letting AI write our test suites.",
      "provider": "openai",
      "model": "gpt-5",
      "outputMode": "text",
      "position": {
        "x": 500,
        "y": 520
      },
      "createdAt": 1778710000000,
      "updatedAt": 1778710000000,
      "output": {
        "status": "success",
        "text": "**The strongest case against is that this codifies sloppy review as the new normal.**\n\nThe PR-review failure mode is well-documented: when authors stop trusting AI output, they skim. When they trust it, they rubber-stamp. Neither produces good tests. You'll get tests that *look* comprehensive and silently rot.\n\nConcrete objections:\n\n1. **The tests will be locally plausible and globally wrong.** Sonnet doesn't know that the auth middleware in this codebase already handles 401s for you, so it'll write a 401 test that duplicates middleware coverage. You're inflating coverage metrics without adding signal.\n\n2. **The 25% feature-time figure is misleading.** Half of that quarter is engineers *thinking about the contract* while writing tests \u2014 catching design bugs before they ship. Skip that step and you'll catch them in production instead. The cost moves; it doesn't disappear.\n\n3. **A snippet library + Copilot rules captures 80% of the value at 10% of the risk.** You already have Copilot. The marginal improvement from a 3-week custom pipeline over \"better prompts + a `tests-for-handlers.md` rule file\" is real but not 3-week-engineering real.",
        "durationMs": 4900
      },
      "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
      "dimensions": {
        "width": 360,
        "height": 480
      }
    },
    {
      "id": "cell_ai_3",
      "type": "ai",
      "title": "Blindspot",
      "instruction": "What's the failure mode no one in the RFC is naming?",
      "provider": "xai",
      "model": "grok-4",
      "outputMode": "text",
      "position": {
        "x": 900,
        "y": 520
      },
      "createdAt": 1778710000000,
      "updatedAt": 1778710000000,
      "output": {
        "status": "success",
        "text": "**The thing no one is naming: this isn't a tooling decision, it's a hiring signal.**\n\nWhichever team owns this becomes the team that defines *what good tests look like* for the company. If devx ships it, they'll bias toward tests that are easy to generate. If a product team ships it, they'll bias toward tests that catch regressions in their own surface. Both are local maxima.\n\nTwo failure modes the RFC doesn't mention:\n\n1. **Junior engineers will stop learning how to write tests.** Two years from now you'll have mid-level engineers who can review an AI test but can't write a tricky one from scratch. That's a real capability loss, not a productivity gain. The RFC needs a story for how the AI-generated tests *teach*, not just *substitute*.\n\n2. **The cheatsheet becomes load-bearing infrastructure with no owner.** Once Sonnet's output depends on a project-wide testing-style document, that document is now a critical artifact. Who updates it when patterns evolve? Who reviews it when style preferences change? You're adding a new ownership boundary that the RFC treats as a one-time write.",
        "durationMs": 5250
      },
      "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
      "dimensions": {
        "width": 360,
        "height": 480
      }
    },
    {
      "id": "cell_ai_4",
      "type": "ai",
      "title": "Verdict object (structured)",
      "instruction": "Read the RFC and the three perspectives, then output a verdict object: { verdict (pilot|reject|ship_now|wait_for_X), confidence (1-10), kill_criteria (specific conditions that would force a reversal), first_owner }.",
      "provider": "anthropic",
      "model": "claude-sonnet-4-20250514",
      "outputMode": "structured",
      "position": {
        "x": 1300,
        "y": 520
      },
      "createdAt": 1778710000000,
      "updatedAt": 1778710000000,
      "output": {
        "status": "success",
        "text": "{\"verdict\": \"pilot\", \"confidence\": 7, \"kill_criteria\": \"(1) >15% of AI tests need rewrite during review for 3 consecutive sprints. (2) Coverage rises but escaped-defect rate stays flat after 6 sprints. (3) Junior engineers self-report decline in test-writing confidence.\", \"first_owner\": \"devx team (Beck), with monthly review by platform-eng\"}",
        "durationMs": 5600
      },
      "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
      "dimensions": {
        "width": 360,
        "height": 480
      },
      "schemaMode": "single",
      "schema": [
        {
          "name": "verdict",
          "type": "string"
        },
        {
          "name": "confidence",
          "type": "number"
        },
        {
          "name": "kill_criteria",
          "type": "string"
        },
        {
          "name": "first_owner",
          "type": "string"
        }
      ]
    }
  ],
  "executionMode": "manual"
} as const
