// AUTO-GENERATED. Source: scripts/build-patchbay-demos.py
// Two demo workspaces seeded onto every Vercel cold-start instance.
//   [0] Active landing: "Should AI agents write our test suites?"
//   [1] Sibling shown in sidepanel: "Risk gate for an infra change"
//       — the only demo that exercises all three primitives (Source, AI, Code)
//
export const DEMO_WORKSPACES = [
  {
    "version": 12,
    "id": "patchbay_demo_ai_tests_rfc",
    "name": "Demo \u00b7 Should AI agents write our test suites?",
    "nodes": [],
    "connections": [
      {
        "id": "a_conn_1",
        "sourceId": "cell_src_rfc",
        "targetId": "cell_ai_1",
        "label": "source",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "a_conn_2",
        "sourceId": "cell_src_rfc",
        "targetId": "cell_ai_2",
        "label": "source",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "a_conn_3",
        "sourceId": "cell_src_rfc",
        "targetId": "cell_ai_3",
        "label": "source",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "a_conn_4",
        "sourceId": "cell_src_rfc",
        "targetId": "cell_ai_4",
        "label": "source",
        "createdAt": 1778712000000,
        "gate": "open"
      }
    ],
    "viewport": {
      "x": -20,
      "y": 0,
      "zoom": 0.62
    },
    "cells": [
      {
        "id": "cell_src_rfc",
        "type": "source",
        "title": "RFC: AI-written test suites",
        "content": "## RFC: Let Claude write the test suite for new endpoints\n\n**Author:** platform-eng@  \u00b7  **Status:** Draft  \u00b7  **Decide by:** end of sprint\n\n### Current state\n\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\n- Engineers spend ~25% of feature time writing tests\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\n- Senior devs complain about \"happy path bias\" in junior-written tests\n\n### Proposal\n\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\n\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\n- **Owner:** developer-experience team\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\n\n### Decision needed\n\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\nlibrary + Copilot rules instead?\n",
        "position": {
          "x": 560,
          "y": 60
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "## RFC: Let Claude write the test suite for new endpoints\n\n**Author:** platform-eng@  \u00b7  **Status:** Draft  \u00b7  **Decide by:** end of sprint\n\n### Current state\n\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\n- Engineers spend ~25% of feature time writing tests\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\n- Senior devs complain about \"happy path bias\" in junior-written tests\n\n### Proposal\n\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\n\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\n- **Owner:** developer-experience team\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\n\n### Decision needed\n\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\nlibrary + Copilot rules instead?\n",
          "durationMs": 0
        },
        "dimensions": {
          "width": 420,
          "height": 360
        }
      },
      {
        "id": "cell_ai_1",
        "type": "ai",
        "title": "Steelman: pilot it",
        "instruction": "Steelman the case FOR letting AI write our test suites.",
        "provider": "anthropic",
        "model": "claude-sonnet-4-20250514",
        "outputMode": "text",
        "position": {
          "x": 100,
          "y": 520
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "**The strongest case for shipping this isn't that AI writes better tests \u2014 it's that it changes which tests get written.**\n\nHand-written tests are biased toward the cases the author *thought of*. AI-generated tests are biased toward the cases the *handler's surface area implies*. Different bias, broader coverage.\n\nThree load-bearing arguments:\n\n1. **It moves the bottleneck.** Right now the slow step is *writing*, not *reviewing*. Inverting that lets a senior reviewer go through 4\u00d7 the routes per hour. Your senior bench becomes more leveraged, not more loaded.\n\n2. **Error-path coverage will jump.** Engineers under deadline pressure skip the 401/403/422 branches. A Sonnet given the OpenAPI schema *always* writes them. The 71% coverage problem is concentrated exactly where AI is consistent and humans are inconsistent.\n\n3. **The kill-switch makes it cheap to try.** Env flag, 5-minute revert. The downside of being wrong about this for one sprint is 3 weeks of work; the downside of being right and not trying is 18 months of slower delivery.",
          "durationMs": 4550
        },
        "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
        "dimensions": {
          "width": 360,
          "height": 480
        }
      },
      {
        "id": "cell_ai_2",
        "type": "ai",
        "title": "Steelman: don't",
        "instruction": "Steelman the case AGAINST letting AI write our test suites.",
        "provider": "openai",
        "model": "gpt-5",
        "outputMode": "text",
        "position": {
          "x": 500,
          "y": 520
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "**The strongest case against is that this codifies sloppy review as the new normal.**\n\nThe PR-review failure mode is well-documented: when authors stop trusting AI output, they skim. When they trust it, they rubber-stamp. Neither produces good tests. You'll get tests that *look* comprehensive and silently rot.\n\nConcrete objections:\n\n1. **The tests will be locally plausible and globally wrong.** Sonnet doesn't know that the auth middleware in this codebase already handles 401s for you, so it'll write a 401 test that duplicates middleware coverage. You're inflating coverage metrics without adding signal.\n\n2. **The 25% feature-time figure is misleading.** Half of that quarter is engineers *thinking about the contract* while writing tests \u2014 catching design bugs before they ship. Skip that step and you'll catch them in production instead. The cost moves; it doesn't disappear.\n\n3. **A snippet library + Copilot rules captures 80% of the value at 10% of the risk.** You already have Copilot. The marginal improvement from a 3-week custom pipeline over \"better prompts + a `tests-for-handlers.md` rule file\" is real but not 3-week-engineering real.",
          "durationMs": 4900
        },
        "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
        "dimensions": {
          "width": 360,
          "height": 480
        }
      },
      {
        "id": "cell_ai_3",
        "type": "ai",
        "title": "Blindspot",
        "instruction": "What's the failure mode no one in the RFC is naming?",
        "provider": "xai",
        "model": "grok-4",
        "outputMode": "text",
        "position": {
          "x": 900,
          "y": 520
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "**The thing no one is naming: this isn't a tooling decision, it's a hiring signal.**\n\nWhichever team owns this becomes the team that defines *what good tests look like* for the company. If devx ships it, they'll bias toward tests that are easy to generate. If a product team ships it, they'll bias toward tests that catch regressions in their own surface. Both are local maxima.\n\nTwo failure modes the RFC doesn't mention:\n\n1. **Junior engineers will stop learning how to write tests.** Two years from now you'll have mid-level engineers who can review an AI test but can't write a tricky one from scratch. That's a real capability loss, not a productivity gain. The RFC needs a story for how the AI-generated tests *teach*, not just *substitute*.\n\n2. **The cheatsheet becomes load-bearing infrastructure with no owner.** Once Sonnet's output depends on a project-wide testing-style document, that document is now a critical artifact. Who updates it when patterns evolve? Who reviews it when style preferences change? You're adding a new ownership boundary that the RFC treats as a one-time write.",
          "durationMs": 5250
        },
        "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
        "dimensions": {
          "width": 360,
          "height": 480
        }
      },
      {
        "id": "cell_ai_4",
        "type": "ai",
        "title": "Verdict object (structured)",
        "instruction": "Read the RFC and three perspectives, then output a verdict.",
        "provider": "anthropic",
        "model": "claude-sonnet-4-20250514",
        "outputMode": "structured",
        "position": {
          "x": 1300,
          "y": 520
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "{\"verdict\": \"pilot\", \"confidence\": 7, \"kill_criteria\": \"(1) >15% of AI tests need rewrite during review for 3 consecutive sprints. (2) Coverage rises but escaped-defect rate stays flat after 6 sprints. (3) Junior engineers self-report decline in test-writing confidence.\", \"first_owner\": \"devx team (Beck), with monthly review by platform-eng\"}",
          "durationMs": 5600
        },
        "lastInputHash": "[[\"RFC: AI-written test suites\",\"## RFC: Let Claude write the test suite for new endpoints\\n\\n**Author:** platform-eng@  \\u00b7  **Status:** Draft  \\u00b7  **Decide by:** end of sprint\\n\\n### Current state\\n\\n- Every new HTTP handler ships with a hand-written test file (Vitest + supertest)\\n- Engineers spend ~25% of feature time writing tests\\n- Coverage hovers at 71%; the gaps are concentrated in error paths and edge cases\\n- Senior devs complain about \\\"happy path bias\\\" in junior-written tests\\n\\n### Proposal\\n\\nFor each new route, the PR includes an autogenerated `*.spec.ts` produced by Claude\\nSonnet given (a) the handler source, (b) the route's OpenAPI schema, and (c) a\\nproject-wide testing-style cheatsheet. Authors review and edit before merge.\\n\\n- **Estimated build:** 3 weeks (prompt, eval harness, CI integration)\\n- **Owner:** developer-experience team\\n- **Reversibility:** disable by env flag in 5 minutes; no DB or runtime coupling\\n\\n### Decision needed\\n\\nGreenlight the pilot for Q3, or invest the same eng-weeks in a hand-tuned snippet\\nlibrary + Copilot rules instead?\\n\"]]",
        "dimensions": {
          "width": 360,
          "height": 480
        },
        "schemaMode": "single",
        "schema": [
          {
            "name": "verdict",
            "type": "string"
          },
          {
            "name": "confidence",
            "type": "number"
          },
          {
            "name": "kill_criteria",
            "type": "string"
          },
          {
            "name": "first_owner",
            "type": "string"
          }
        ]
      }
    ],
    "executionMode": "manual"
  },
  {
    "version": 12,
    "id": "patchbay_demo_infra_risk_gate",
    "name": "Demo \u00b7 Risk gate for an infra change",
    "nodes": [],
    "connections": [
      {
        "id": "b_c1",
        "sourceId": "cell_src_tf",
        "targetId": "cell_ai_cost",
        "label": "source",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "b_c2",
        "sourceId": "cell_src_tf",
        "targetId": "cell_ai_blast",
        "label": "source",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "b_c3",
        "sourceId": "cell_src_tf",
        "targetId": "cell_ai_sec",
        "label": "source",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "b_c4",
        "sourceId": "cell_ai_cost",
        "targetId": "cell_code_policy",
        "label": "Cost",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "b_c5",
        "sourceId": "cell_ai_blast",
        "targetId": "cell_code_policy",
        "label": "Blast",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "b_c6",
        "sourceId": "cell_ai_sec",
        "targetId": "cell_code_policy",
        "label": "Security",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "b_c7",
        "sourceId": "cell_code_policy",
        "targetId": "cell_ai_comment",
        "label": "Policy gate",
        "createdAt": 1778712000000,
        "gate": "open"
      },
      {
        "id": "b_c8",
        "sourceId": "cell_src_tf",
        "targetId": "cell_ai_comment",
        "label": "Terraform plan \u2014 analytics DB upgrade",
        "createdAt": 1778712000000,
        "gate": "open"
      }
    ],
    "viewport": {
      "x": -40,
      "y": -10,
      "zoom": 0.5
    },
    "cells": [
      {
        "id": "cell_src_tf",
        "type": "source",
        "title": "Terraform plan \u2014 analytics DB upgrade",
        "content": "## Terraform plan: upgrade analytics DB\n\n**PR:** platform/terraform#482  \u00b7  **Author:** data-platform@  \u00b7  **Target:** prod\n\nUpgrading the analytics warehouse from a single `db.r6g.large` to a 3-node\n`db.r6g.4xlarge` Aurora cluster to handle Q4 forecasted load (3\u00d7 ingest, 2\u00d7 query\nconcurrency).\n\n```hcl\n- resource \"aws_rds_cluster\" \"analytics\" {\n-   cluster_identifier = \"analytics\"\n-   engine             = \"aurora-postgresql\"\n-   engine_version     = \"15.4\"\n-   instance_class     = \"db.r6g.large\"   # 2 vCPU, 16 GB\n-   instances          = 1\n-   storage_encrypted  = true\n- }\n\n+ resource \"aws_rds_cluster\" \"analytics_v2\" {\n+   cluster_identifier = \"analytics-v2\"\n+   engine             = \"aurora-postgresql\"\n+   engine_version     = \"16.2\"\n+   instance_class     = \"db.r6g.4xlarge\"  # 16 vCPU, 128 GB\n+   instances          = 3\n+   storage_encrypted  = true\n+   deletion_protection = false\n+ }\n```\n\nCutover plan: snapshot old cluster \u2192 restore into new \u2192 45-min DNS swap \u2192\ndelete old cluster after 7-day verification window.\n",
        "position": {
          "x": 560,
          "y": 40
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "## Terraform plan: upgrade analytics DB\n\n**PR:** platform/terraform#482  \u00b7  **Author:** data-platform@  \u00b7  **Target:** prod\n\nUpgrading the analytics warehouse from a single `db.r6g.large` to a 3-node\n`db.r6g.4xlarge` Aurora cluster to handle Q4 forecasted load (3\u00d7 ingest, 2\u00d7 query\nconcurrency).\n\n```hcl\n- resource \"aws_rds_cluster\" \"analytics\" {\n-   cluster_identifier = \"analytics\"\n-   engine             = \"aurora-postgresql\"\n-   engine_version     = \"15.4\"\n-   instance_class     = \"db.r6g.large\"   # 2 vCPU, 16 GB\n-   instances          = 1\n-   storage_encrypted  = true\n- }\n\n+ resource \"aws_rds_cluster\" \"analytics_v2\" {\n+   cluster_identifier = \"analytics-v2\"\n+   engine             = \"aurora-postgresql\"\n+   engine_version     = \"16.2\"\n+   instance_class     = \"db.r6g.4xlarge\"  # 16 vCPU, 128 GB\n+   instances          = 3\n+   storage_encrypted  = true\n+   deletion_protection = false\n+ }\n```\n\nCutover plan: snapshot old cluster \u2192 restore into new \u2192 45-min DNS swap \u2192\ndelete old cluster after 7-day verification window.\n",
          "durationMs": 0
        },
        "dimensions": {
          "width": 420,
          "height": 380
        }
      },
      {
        "id": "cell_ai_cost",
        "type": "ai",
        "title": "Cost",
        "instruction": "Estimate the monthly and annualized cost delta for this Terraform plan. Use current AWS list prices for db.r6g.* instances in us-east-1.",
        "provider": "anthropic",
        "model": "claude-sonnet-4-20250514",
        "outputMode": "structured",
        "schemaMode": "single",
        "schema": [
          {
            "name": "current_monthly_usd",
            "type": "number"
          },
          {
            "name": "proposed_monthly_usd",
            "type": "number"
          },
          {
            "name": "delta_monthly_usd",
            "type": "number"
          },
          {
            "name": "annualized_delta_usd",
            "type": "number"
          },
          {
            "name": "confidence",
            "type": "number"
          }
        ],
        "position": {
          "x": 80,
          "y": 500
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "{\"current_monthly_usd\": 145, \"proposed_monthly_usd\": 4380, \"delta_monthly_usd\": 4235, \"annualized_delta_usd\": 50820, \"confidence\": 8}",
          "durationMs": 3100
        },
        "lastInputHash": "[[\"Terraform plan \u2014 analytics DB upgrade\",\"## Terraform plan: upgrade analytics DB\\n\\n**PR:** platform/terraform#482  \\u00b7  **Author:** data-platform@  \\u00b7  **Target:** prod\\n\\nUpgrading the analytics warehouse from a single `db.r6g.large` to a 3-node\\n`db.r6g.4xlarge` Aurora cluster to handle Q4 forecasted load (3\\u00d7 ingest, 2\\u00d7 query\\nconcurrency).\\n\\n```hcl\\n- resource \\\"aws_rds_cluster\\\" \\\"analytics\\\" {\\n-   cluster_identifier = \\\"analytics\\\"\\n-   engine             = \\\"aurora-postgresql\\\"\\n-   engine_version     = \\\"15.4\\\"\\n-   instance_class     = \\\"db.r6g.large\\\"   # 2 vCPU, 16 GB\\n-   instances          = 1\\n-   storage_encrypted  = true\\n- }\\n\\n+ resource \\\"aws_rds_cluster\\\" \\\"analytics_v2\\\" {\\n+   cluster_identifier = \\\"analytics-v2\\\"\\n+   engine             = \\\"aurora-postgresql\\\"\\n+   engine_version     = \\\"16.2\\\"\\n+   instance_class     = \\\"db.r6g.4xlarge\\\"  # 16 vCPU, 128 GB\\n+   instances          = 3\\n+   storage_encrypted  = true\\n+   deletion_protection = false\\n+ }\\n```\\n\\nCutover plan: snapshot old cluster \\u2192 restore into new \\u2192 45-min DNS swap \\u2192\\ndelete old cluster after 7-day verification window.\\n\"]]",
        "dimensions": {
          "width": 360,
          "height": 360
        }
      },
      {
        "id": "cell_ai_blast",
        "type": "ai",
        "title": "Blast",
        "instruction": "Estimate the blast radius of this Terraform plan. List affected services and quantify downtime + reversibility window.",
        "provider": "xai",
        "model": "grok-4",
        "outputMode": "structured",
        "schemaMode": "single",
        "schema": [
          {
            "name": "blast_radius",
            "type": "string"
          },
          {
            "name": "services_affected",
            "type": "string"
          },
          {
            "name": "downtime_minutes",
            "type": "number"
          },
          {
            "name": "reversibility",
            "type": "string"
          }
        ],
        "position": {
          "x": 480,
          "y": 500
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "{\"blast_radius\": \"high\", \"services_affected\": \"analytics-api, weekly-reports, customer-dashboard, exec-kpi-feed\", \"downtime_minutes\": 45, \"reversibility\": \"Destructive \\u2014 old cluster deleted after 7-day window. PITR available within that window; after day 7, rollback would require restoring from logical backup (~4 hour RTO).\"}",
          "durationMs": 3800
        },
        "lastInputHash": "[[\"Terraform plan \u2014 analytics DB upgrade\",\"## Terraform plan: upgrade analytics DB\\n\\n**PR:** platform/terraform#482  \\u00b7  **Author:** data-platform@  \\u00b7  **Target:** prod\\n\\nUpgrading the analytics warehouse from a single `db.r6g.large` to a 3-node\\n`db.r6g.4xlarge` Aurora cluster to handle Q4 forecasted load (3\\u00d7 ingest, 2\\u00d7 query\\nconcurrency).\\n\\n```hcl\\n- resource \\\"aws_rds_cluster\\\" \\\"analytics\\\" {\\n-   cluster_identifier = \\\"analytics\\\"\\n-   engine             = \\\"aurora-postgresql\\\"\\n-   engine_version     = \\\"15.4\\\"\\n-   instance_class     = \\\"db.r6g.large\\\"   # 2 vCPU, 16 GB\\n-   instances          = 1\\n-   storage_encrypted  = true\\n- }\\n\\n+ resource \\\"aws_rds_cluster\\\" \\\"analytics_v2\\\" {\\n+   cluster_identifier = \\\"analytics-v2\\\"\\n+   engine             = \\\"aurora-postgresql\\\"\\n+   engine_version     = \\\"16.2\\\"\\n+   instance_class     = \\\"db.r6g.4xlarge\\\"  # 16 vCPU, 128 GB\\n+   instances          = 3\\n+   storage_encrypted  = true\\n+   deletion_protection = false\\n+ }\\n```\\n\\nCutover plan: snapshot old cluster \\u2192 restore into new \\u2192 45-min DNS swap \\u2192\\ndelete old cluster after 7-day verification window.\\n\"]]",
        "dimensions": {
          "width": 360,
          "height": 360
        }
      },
      {
        "id": "cell_ai_sec",
        "type": "ai",
        "title": "Security",
        "instruction": "Evaluate the security posture changes in this Terraform plan. Return a risk_level (1-5), specific concerns, and required mitigations.",
        "provider": "openai",
        "model": "gpt-5",
        "outputMode": "structured",
        "schemaMode": "single",
        "schema": [
          {
            "name": "risk_level",
            "type": "number"
          },
          {
            "name": "concerns",
            "type": "string"
          },
          {
            "name": "mitigations_required",
            "type": "string"
          }
        ],
        "position": {
          "x": 880,
          "y": 500
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "{\"risk_level\": 3, \"concerns\": \"deletion_protection is set to false on the new cluster. Encryption-at-rest preserved. No new public endpoints. IAM role inherits from old cluster but explicit re-review recommended.\", \"mitigations_required\": \"Set deletion_protection = true before cutover. Add explicit lifecycle policy. Verify analytics-read-replica IAM role permissions on new cluster ARN.\"}",
          "durationMs": 4200
        },
        "lastInputHash": "[[\"Terraform plan \u2014 analytics DB upgrade\",\"## Terraform plan: upgrade analytics DB\\n\\n**PR:** platform/terraform#482  \\u00b7  **Author:** data-platform@  \\u00b7  **Target:** prod\\n\\nUpgrading the analytics warehouse from a single `db.r6g.large` to a 3-node\\n`db.r6g.4xlarge` Aurora cluster to handle Q4 forecasted load (3\\u00d7 ingest, 2\\u00d7 query\\nconcurrency).\\n\\n```hcl\\n- resource \\\"aws_rds_cluster\\\" \\\"analytics\\\" {\\n-   cluster_identifier = \\\"analytics\\\"\\n-   engine             = \\\"aurora-postgresql\\\"\\n-   engine_version     = \\\"15.4\\\"\\n-   instance_class     = \\\"db.r6g.large\\\"   # 2 vCPU, 16 GB\\n-   instances          = 1\\n-   storage_encrypted  = true\\n- }\\n\\n+ resource \\\"aws_rds_cluster\\\" \\\"analytics_v2\\\" {\\n+   cluster_identifier = \\\"analytics-v2\\\"\\n+   engine             = \\\"aurora-postgresql\\\"\\n+   engine_version     = \\\"16.2\\\"\\n+   instance_class     = \\\"db.r6g.4xlarge\\\"  # 16 vCPU, 128 GB\\n+   instances          = 3\\n+   storage_encrypted  = true\\n+   deletion_protection = false\\n+ }\\n```\\n\\nCutover plan: snapshot old cluster \\u2192 restore into new \\u2192 45-min DNS swap \\u2192\\ndelete old cluster after 7-day verification window.\\n\"]]",
        "dimensions": {
          "width": 360,
          "height": 360
        }
      },
      {
        "id": "cell_code_policy",
        "type": "code",
        "title": "Policy gate",
        "code": "// Deterministic policy gate \u2014 AI cells estimate, this cell decides.\n// Each input arrives as a JSON-string from a structured-output AI cell.\nconst cost  = JSON.parse(input.Cost);\nconst blast = JSON.parse(input.Blast);\nconst sec   = JSON.parse(input.Security);\n\nconst rules = {\n  cost_delta_under_500_usd: cost.delta_monthly_usd < 500,\n  blast_radius_not_high:    blast.blast_radius !== \"high\",\n  security_risk_below_4:    sec.risk_level < 4,\n};\n\nconst failing = Object.entries(rules)\n  .filter(([, ok]) => !ok)\n  .map(([rule]) => rule);\n\nreturn JSON.stringify({\n  auto_approve: failing.length === 0,\n  human_review_required: failing.length > 0,\n  failing_rules: failing,\n  passing_rules: Object.keys(rules).filter(r => !failing.includes(r)),\n  cost_delta_monthly_usd: cost.delta_monthly_usd,\n  blast_radius: blast.blast_radius,\n  security_risk_level: sec.risk_level,\n}, null, 2);\n",
        "timeoutMs": 5000,
        "position": {
          "x": 480,
          "y": 920
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "{\n  \"auto_approve\": false,\n  \"human_review_required\": true,\n  \"failing_rules\": [\n    \"cost_delta_under_500_usd\",\n    \"blast_radius_not_high\"\n  ],\n  \"passing_rules\": [\n    \"security_risk_below_4\"\n  ],\n  \"cost_delta_monthly_usd\": 4235,\n  \"blast_radius\": \"high\",\n  \"security_risk_level\": 3\n}",
          "durationMs": 4
        },
        "lastInputHash": "[[\"Cost\",\"{\\\"current_monthly_usd\\\": 145, \\\"proposed_monthly_usd\\\": 4380, \\\"delta_monthly_usd\\\": 4235, \\\"annualized_delta_usd\\\": 50820, \\\"confidence\\\": 8}\"],[\"Blast\",\"{\\\"blast_radius\\\": \\\"high\\\", \\\"services_affected\\\": \\\"analytics-api, weekly-reports, customer-dashboard, exec-kpi-feed\\\", \\\"downtime_minutes\\\": 45, \\\"reversibility\\\": \\\"Destructive \\\\u2014 old cluster deleted after 7-day window. PITR available within that window; after day 7, rollback would require restoring from logical backup (~4 hour RTO).\\\"}\"],[\"Security\",\"{\\\"risk_level\\\": 3, \\\"concerns\\\": \\\"deletion_protection is set to false on the new cluster. Encryption-at-rest preserved. No new public endpoints. IAM role inherits from old cluster but explicit re-review recommended.\\\", \\\"mitigations_required\\\": \\\"Set deletion_protection = true before cutover. Add explicit lifecycle policy. Verify analytics-read-replica IAM role permissions on new cluster ARN.\\\"}\"]]",
        "dimensions": {
          "width": 480,
          "height": 320
        }
      },
      {
        "id": "cell_ai_comment",
        "type": "ai",
        "title": "Review comment",
        "instruction": "Given the Terraform plan and the deterministic policy gate output, write the GitHub PR review comment. If auto_approve is true, write a concise approval. If auto_approve is false, write a blocking review that cites each failing rule with the specific number that failed it, and recommend concrete next steps.",
        "provider": "anthropic",
        "model": "claude-sonnet-4-20250514",
        "outputMode": "text",
        "position": {
          "x": 1040,
          "y": 920
        },
        "createdAt": 1778712000000,
        "updatedAt": 1778712000000,
        "output": {
          "status": "success",
          "text": "## Blocking review required \u2014 2 of 3 policy gates failed\n\n**Auto-approval declined.** This change exceeds the bar for unsupervised merge.\n\n### Failing rules\n\n- **`cost_delta_under_500_usd`** \u2014 proposed change adds **$4,235/month** ($50,820/yr) over the current cluster. Threshold is $500/mo for auto-approval.\n- **`blast_radius_not_high`** \u2014 touches 4 downstream services (`analytics-api`, `weekly-reports`, `customer-dashboard`, `exec-kpi-feed`). Reversibility window closes after day 7 (snapshot retention).\n\n### Passing rules\n\n- \u2705 `security_risk_below_4` \u2014 risk level 3/5 (deletion_protection currently set to `false` on the new cluster, but flagged with explicit mitigation).\n\n### Recommended next steps for the human reviewer\n\n1. **Sign-off on the cost line** \u2014 this is a $50K/yr decision. Loop in finance or the BU sponsor explicitly; don't let it slide through as an infra ticket.\n2. **Set `deletion_protection = true`** before applying the plan, per the security reviewer's mitigation. The current value of `false` on a load-bearing analytics cluster is the same anti-pattern that caused the March '26 data-platform incident.\n3. **Confirm the 7-day rollback window** is acceptable to weekly-reports \u2014 that team's last incident response took 11 days to fully resolve, so the snapshot retention may be too short.\n\nIf those three boxes get checked, this change is shippable. If not, push back on the upgrade scope (consider sizing to `db.r6g.2xlarge` first, validate query load, then scale up).",
          "durationMs": 6700
        },
        "lastInputHash": "[[\"Policy gate\",\"{\\n  \\\"auto_approve\\\": false,\\n  \\\"human_review_required\\\": true,\\n  \\\"failing_rules\\\": [\\n    \\\"cost_delta_under_500_usd\\\",\\n    \\\"blast_radius_not_high\\\"\\n  ],\\n  \\\"passing_rules\\\": [\\n    \\\"security_risk_below_4\\\"\\n  ],\\n  \\\"cost_delta_monthly_usd\\\": 4235,\\n  \\\"blast_radius\\\": \\\"high\\\",\\n  \\\"security_risk_level\\\": 3\\n}\"],[\"Terraform plan \u2014 analytics DB upgrade\",\"## Terraform plan: upgrade analytics DB\\n\\n**PR:** platform/terraform#482  \\u00b7  **Author:** data-platform@  \\u00b7  **Target:** prod\\n\\nUpgrading the analytics warehouse from a single `db.r6g.large` to a 3-node\\n`db.r6g.4xlarge` Aurora cluster to handle Q4 forecasted load (3\\u00d7 ingest, 2\\u00d7 query\\nconcurrency).\\n\\n```hcl\\n- resource \\\"aws_rds_cluster\\\" \\\"analytics\\\" {\\n-   cluster_identifier = \\\"analytics\\\"\\n-   engine             = \\\"aurora-postgresql\\\"\\n-   engine_version     = \\\"15.4\\\"\\n-   instance_class     = \\\"db.r6g.large\\\"   # 2 vCPU, 16 GB\\n-   instances          = 1\\n-   storage_encrypted  = true\\n- }\\n\\n+ resource \\\"aws_rds_cluster\\\" \\\"analytics_v2\\\" {\\n+   cluster_identifier = \\\"analytics-v2\\\"\\n+   engine             = \\\"aurora-postgresql\\\"\\n+   engine_version     = \\\"16.2\\\"\\n+   instance_class     = \\\"db.r6g.4xlarge\\\"  # 16 vCPU, 128 GB\\n+   instances          = 3\\n+   storage_encrypted  = true\\n+   deletion_protection = false\\n+ }\\n```\\n\\nCutover plan: snapshot old cluster \\u2192 restore into new \\u2192 45-min DNS swap \\u2192\\ndelete old cluster after 7-day verification window.\\n\"]]",
        "dimensions": {
          "width": 540,
          "height": 480
        }
      }
    ],
    "executionMode": "manual"
  }
] as const

// Back-compat shim — hardening checks that pre-date the multi-workspace seed
// import DEMO_WORKSPACE (singular). Keep them working; new code should use
// DEMO_WORKSPACES and isDemoWorkspaceId() below.
export const DEMO_WORKSPACE = DEMO_WORKSPACES[0]

const DEMO_IDS: ReadonlySet<string> = new Set(DEMO_WORKSPACES.map((w) => w.id))

/** True iff the given workspace id is a bundled demo and should be read-only. */
export function isDemoWorkspaceId(id: string): boolean {
  return DEMO_IDS.has(id)
}
